### PR TITLE
fix issue#73

### LINKED ISSUE #73: git for-each-ref format options can cause the changelog to be empty
# Issue

`git for-each-ref --sort=taggerdate --format='%(tag)' refs/tags` just outputs `\n` chars if a project is using the commit object when tagging.

After discussion with @dvmonroe, making the format in the above command configurable seems to mitigate the issue. 

## Environment

- Ruby **2.5.3**
- Rails **5.2.2**
- release-notes **3.0.0**

## Current behavior

`git for-each-ref --sort=taggerdate --format='%(tag)' refs/tags` fails and an empty changelog is created. The output of this command is just `\n` characters on a project that uses the commit object when tagging.

## Expected behavior

`git for-each-ref --sort=taggerdate --format='%(tag)' refs/tags` will return an array of tags.

### PR DESCRIPTION
**Pull request by andrewmcodes**
# Bug fix

## Description

Allow user to specify format options for `git for-each-ref`, which will break under non-traditional tagging setups.

Fixes #73

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have rebased the branch with the latest code from master
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, and at the top of new interactors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] The build is passing

### CODE REVIEW

File: spec/release/notes/configuration_spec.rb [hunk 1]
```diff
@@ -229,4 +229,19 @@
...
+
+  describe "#for_each_ref_foramt" do
+    context "when for_each_ref_format has been configured" do
+      it "returns the configured value" do
+        Release::Notes.configure { |config| config.for_each_ref_format = "refname:lstrip=-1" }
+        expect(Release::Notes.configuration.for_each_ref_format).to eq "refname:lstrip=-1"
+      end
+    end
+
+    context "when prettify_messages has not been configured" do
```
Comment (dvmonroe) [inline spec/release/notes/configuration_spec.rb]: I'll push a change  to replace the "prettify_messages" text here.
