### PR TITLE
fix cognitive method complexity in log

### LINKED ISSUE #66: Fix "method_complexity" issue in lib/release/notes/log.rb
Method `log_grouped_commits` has a Cognitive Complexity of 9 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/dvmonroe/release-notes/lib/release/notes/log.rb#issue_5c2eda2289c5c00001000026

### PR DESCRIPTION
**Pull request by andrewmcodes**
# Refactor

## Description

Method log_grouped_commits has a Cognitive Complexity of 9 (exceeds 5 allowed). This PR refactors this method to fix this issue.

Fixes #66

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have rebased the branch with the latest code from master
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, and at the top of new interactors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] The build is passing

### CODE REVIEW

File: lib/release/notes/log.rb [hunk 1]
```diff
@@ -114,6 +116,14 @@ def log_grouped_commits(log:, title:) # rubocop:disable Metrics/AbcSize
         digest_title(title: title, log_message: "#{messages.join("\n")}\n")
       end
 
+      # @api private
+      def trim_commit_hashes(commit_hashes)
```
Comment (andrewmcodes) [inline lib/release/notes/log.rb]: Wasn't really sure what the best name for this method was but this made sense to me. Open to suggestions.
