### PR TITLE
Fixes force_rewrite bug

### LINKED ISSUE #56: Default force_rewrite = false is not working correctly
# Issue

if force rewrite is false, we should still be updating the RELEASE_NOTES.md file

## Environment

- release-notes **Latest**

## Current behavior

force_rewrite = false is not updating the output file
## Expected behavior

force_rewrite = false should update the output file with the latest commits. Force rewrite should only be true if someone is starting over, or integrating into a new project.

### PR DESCRIPTION
**Pull request by andrewmcodes**
# Bug Fix

## Description

This should fix the issue described in issue#56. I am sure there is a better way to do this but this resolves the bug and provides a good starting place.

Fixes #56

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have rebased the branch with the latest code from master
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, and at the top of new interactors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] The build is passing

### CODE REVIEW

**Comment by andrewmcodes** [comment]
The unless statement feels a little dirty. It’s a pretty big cognitive load - imo. But sorta makes sense in this context.

File: lib/release/notes/log.rb [hunk 1]
```diff
@@ -67,7 +67,10 @@ def copy_single_tag_of_activity(tag_from:, tag_to: "HEAD")
       # @api private
       def find_last_tag_and_log
         last_tag = system_last_tag.delete!("\n")
-        return false unless system_log(tag_from: last_tag, label: all_labels).present?
+        unless system_log(tag_from: last_tag, label: all_labels).present?
```
Comment (dvmonroe) [inline lib/release/notes/log.rb]: you can prob just make this more syntactical by using an `if...else`  and not returning false. Was rubocop yelling at you?

File: lib/release/notes/log.rb [hunk 2]
```diff
@@ -67,7 +67,10 @@ def copy_single_tag_of_activity(tag_from:, tag_to: "HEAD")
       # @api private
       def find_last_tag_and_log
         last_tag = system_last_tag.delete!("\n")
```
Comment (dvmonroe) [inline lib/release/notes/log.rb]: If rubocop yells at you - you can prob move this to it's own method after rebasing with master:

```ruby
def last_tag
  system_last_tag.strip
end
```

That should reduce complexity.
