### PR TITLE
issue-15 ;B

### LINKED ISSUE #15: Linker not functioning as expected ;B
It looks like linking to sites is not working as expected. When the change log is generated, we would expect to see:
```
[ReleaseNotesDemo #0]](https:\/\/release-notes-demo\/projects\/0) test commit 0
```
but instead we are getting:
```
[ReleaseNotesDemo #0]](https:\/\/release-notes-demo\/projects) test commit 0
```
[Reproduction](https://github.com/andrewmcodes/release-notes-demo/blob/880c38e8c196fb0299f070e49e1853f06c98349a/RELEASE_NOTES.md)

### PR DESCRIPTION
**Pull request by andrewmcodes**
Not super happy about how I ended up fixing this but after wrestling with it for way too long...this is what I came up with to fix #15.

Tested on my demo app and it works as expected.

### CODE REVIEW

File: lib/release/notes/link.rb [hunk 1]
```diff
@@ -35,7 +35,7 @@ def link_lines(lines:)
         def replace(line, issue_number, label, index)
           identifier = "#{label.split(/\s/)[0]} #{issue_number}"
           humanized = "#{link_to_humanize[index]} #{issue_number}"
-          linked = "[#{humanized}](#{link_to_sites[index]})"
+          linked = "[#{humanized}](#{link_to_sites[index]}\/#{issue_number[1..-1].scan(/^[^\[\]]*/)[0]})"
```
Comment (dvmonroe) [inline lib/release/notes/link.rb]: Try `String#tr` or `String#gsub` - scan TMK (w/o benchmarking at the moment) is going to take a lot longer as it's returning an array of occurrences which is why your having to reference the first index in the array.
```suggestion
          linked = "[#{humanized}](#{link_to_sites[index]}\/#{issue_number.tr('^0-9', '')})"
```
or
```suggestion
          linked = "[#{humanized}](#{link_to_sites[index]}\/#{issue_number.gsub(/[^\d]/, '')})"
```

From a quick google search i believe tr is the fastest.
